# Generated by Django 5.0 on 2023-12-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosticservicetracker",
            name="notes",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
