# Generated by Django 5.0 on 2023-12-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_alter_diagnosticservicetracker_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosticservice",
            name="duration",
            field=models.IntegerField(help_text="Duration in days"),
        ),
    ]
