# Generated by Django 5.0 on 2023-12-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="diagnostic_request",
        ),
        migrations.AddField(
            model_name="payment",
            name="diagnostic_requests",
            field=models.ManyToManyField(
                blank=True, related_name="payments", to="services.diagnosticrequest"
            ),
        ),
    ]
