# Generated by Django 5.0 on 2023-12-07 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0002_remove_user_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labstaff",
            name="start_date",
        ),
    ]
